import { Mail, ShieldCheck, AlertTriangle } from "lucide-react";
import InfoCard from "../components/InfoCard";

export default function About() {
  return (
    <section className="py-20">
      <div className="mx-auto max-w-3xl px-6">
        <h1 className="mb-8 text-3xl font-bold text-slate-900">About UniSynthe</h1>

        <div className="space-y-6 text-slate-600 leading-relaxed">
          <h2 className="text-lg font-semibold text-slate-900">Our Mission</h2>
          <p>
            UniSynthe is a developer-focused software platform designed to help applications
            implement user notifications and account security features without building their
            own infrastructure.
          </p>
          <p>
            The platform provides APIs for application events such as authentication, account
            recovery, and security monitoring. Notification capabilities exist only as a
            component of these application workflows.
          </p>

          <h2 className="text-lg font-semibold text-slate-900">What We Do</h2>
          <ul className="list-disc space-y-2 pl-6">
            <li>
              <strong>Account Security:</strong> Verification codes, authentication events,
              password recovery flows, and suspicious activity alerts — all triggered by
              application logic, not by end users directly.
            </li>
            <li>
              <strong>Application Notifications:</strong> Event-driven transactional notifications
              for system events, status changes, and service alerts generated by integrated applications.
            </li>
            <li>
              <strong>Fraud Detection:</strong> IP-to-location resolution, proxy/VPN detection,
              and session-based risk scoring to protect application accounts.
            </li>
          </ul>

          <h2 className="text-lg font-semibold text-slate-900">What We Don't Do</h2>
          <ul className="list-disc space-y-2 pl-6">
            <li>We do not operate a public notification network or open messaging gateway.</li>
            <li>We do not provide standalone notification delivery, resale, or distribution services.</li>
            <li>We do not support promotional, marketing, or unsolicited communications of any kind.</li>
            <li>We do not sell or share end-user data with third parties.</li>
            <li>We do not offer consumer-facing products — UniSynthe is strictly B2B application infrastructure.</li>
          </ul>

          <h2 className="text-lg font-semibold text-slate-900">Security & Compliance</h2>
          <p>
            All API traffic is encrypted via TLS 1.2+. Credentials and sensitive data are encrypted
            at rest using AES-256. We maintain compliance with TCPA, GDPR, CCPA, and CAN-SPAM
            regulations. All notification delivery requires documented end-user consent tied to
            a specific application event.
          </p>
          <p>
            We conduct regular security reviews and maintain an incident response process.
            Abuse reports are investigated within 24 hours.
          </p>

          <h2 className="text-lg font-semibold text-slate-900">Traffic and Abuse Policy</h2>
          <p>
            UniSynthe does not provide open notification access.
            Applications cannot use the platform for promotional outreach, unsolicited
            communication, lead generation, or traffic anonymization.
          </p>
          <p>
            Every integration is reviewed and restricted to transactional and security-related
            use cases. Accounts that violate these restrictions are suspended immediately.
          </p>
        </div>

        {/* Company & Contacts */}
        <div className="mt-16 rounded-2xl border border-slate-200 bg-slate-50 p-8">
          <h2 className="mb-6 text-lg font-semibold text-slate-900">Company & Contacts</h2>
          <div className="space-y-4">
            <InfoCard
              icon={<Mail className="h-5 w-5" />}
              label="General Support"
              value="support@unisynthe.com"
              href="mailto:support@unisynthe.com"
            />
            <InfoCard
              icon={<ShieldCheck className="h-5 w-5" />}
              label="Compliance & Legal"
              value="compliance@unisynthe.com"
              href="mailto:compliance@unisynthe.com"
            />
            <InfoCard
              icon={<AlertTriangle className="h-5 w-5" />}
              label="Abuse Reports"
              value="abuse@unisynthe.com"
              href="mailto:abuse@unisynthe.com"
            />
          </div>
          <p className="mt-6 text-sm text-slate-500">
            Remote-first team · San Francisco Bay Area · United States
          </p>
        </div>
      </div>
    </section>
  );
}
