import { Link } from "react-router-dom";
import {
  KeyRound, ShieldAlert, Bell, Radar,
  ShieldCheck, AlertTriangle, Server, Gauge, LifeBuoy, Lock,
} from "lucide-react";
import FeatureCard from "../components/FeatureCard";
import SectionHeading from "../components/SectionHeading";

const features = [
  {
    icon: <KeyRound className="h-6 w-6" />,
    title: "Account Verification",
    description: "One-time verification codes tied to user authentication events such as registration, login, and password recovery.",
  },
  {
    icon: <ShieldAlert className="h-6 w-6" />,
    title: "Security Alerts",
    description: "Automated notifications about suspicious logins, account changes, and anomalous session activity.",
  },
  {
    icon: <Bell className="h-6 w-6" />,
    title: "System Notifications",
    description: "Application-generated alerts triggered by internal events — service status changes, threshold warnings, and transactional confirmations.",
  },
  {
    icon: <Radar className="h-6 w-6" />,
    title: "Fraud Signals",
    description: "IP and session-based security checks for account protection, proxy detection, and geographic risk assessment.",
  },
];

export default function Home() {
  return (
    <>
      {/* Hero */}
      <section className="bg-gradient-to-b from-slate-50 to-white">
        <div className="mx-auto max-w-4xl px-6 py-24 text-center">
          <h1 className="mb-6 text-4xl font-bold tracking-tight text-slate-900 sm:text-5xl">
            Application Security &amp; Notification APIs for Developers
          </h1>
          <p className="mx-auto mb-10 max-w-2xl text-lg text-slate-600">
            UniSynthe provides APIs that applications use for account verification,
            user notifications, and security alerts. Notification delivery is a built-in
            feature of the platform — not a standalone messaging service.
          </p>
          <div className="flex flex-wrap items-center justify-center gap-4">
            <Link
              to="/request-access"
              className="rounded-lg bg-primary px-6 py-3 text-sm font-medium text-white shadow-sm transition-colors hover:bg-primary-dark"
            >
              Request API Access
            </Link>
            <Link
              to="/about"
              className="rounded-lg border border-slate-300 px-6 py-3 text-sm font-medium text-slate-700 transition-colors hover:border-primary hover:text-primary"
            >
              Learn More
            </Link>
          </div>
          <p className="mt-6 text-xs text-slate-400">
            Currently onboarding a limited number of early integrations.
          </p>
        </div>
      </section>

      {/* How Communication Is Used */}
      <section className="border-y border-slate-200 bg-slate-50 py-20">
        <div className="mx-auto max-w-3xl px-6">
          <SectionHeading title="How notifications work in UniSynthe" />
          <div className="space-y-4 text-slate-600 leading-relaxed">
            <p>
              UniSynthe does not offer bulk notifications, open messaging access, or notification resale.
              All notifications are automatically generated by applications integrated with the platform.
            </p>
            <p>
              End users cannot independently send arbitrary messages.
              All notifications are triggered by application events such as:
            </p>
            <ul className="list-disc space-y-1 pl-6">
              <li>Account registration</li>
              <li>Login verification</li>
              <li>Password reset</li>
              <li>Security alerts</li>
              <li>Transactional system notifications</li>
            </ul>
            <p>
              Every integration is manually reviewed to ensure it meets our acceptable use
              requirements before API credentials are issued.
            </p>
          </div>
        </div>
      </section>

      {/* Use Cases */}
      <section className="py-20">
        <SectionHeading
          title="Built for Application Workflows"
          subtitle="APIs designed for developers who need to add account security and event-driven notifications to their applications."
        />
        <div className="mx-auto grid max-w-6xl gap-6 px-6 sm:grid-cols-2 lg:grid-cols-4">
          {features.map((f) => (
            <FeatureCard key={f.title} {...f} />
          ))}
        </div>
      </section>

      {/* Compliance & Safety */}
      <section className="bg-slate-50 py-20">
        <SectionHeading
          title="Compliance & Safety"
          subtitle="Every notification sent through UniSynthe is tied to an application event, reviewed for compliance, and monitored for abuse."
        />
        <div className="mx-auto max-w-4xl px-6">
          <div className="grid gap-6 sm:grid-cols-2">
            <div className="rounded-2xl border border-slate-200 bg-white p-6">
              <Lock className="mb-3 h-6 w-6 text-primary" />
              <h3 className="mb-2 font-semibold text-slate-900">Event-Driven Only</h3>
              <p className="text-sm leading-relaxed text-slate-600">
                All notifications are triggered by verified application events — authentication,
                account recovery, security alerts. The platform does not support user-initiated
                or promotional communications.
              </p>
            </div>
            <div className="rounded-2xl border border-slate-200 bg-white p-6">
              <ShieldCheck className="mb-3 h-6 w-6 text-primary" />
              <h3 className="mb-2 font-semibold text-slate-900">STOP / HELP Compliance</h3>
              <p className="text-sm leading-relaxed text-slate-600">
                All notification channels honor STOP and HELP keywords. Opt-out requests
                are processed automatically. Non-compliance results in immediate suspension.
              </p>
            </div>
            <div className="rounded-2xl border border-slate-200 bg-white p-6">
              <AlertTriangle className="mb-3 h-6 w-6 text-primary" />
              <h3 className="mb-2 font-semibold text-slate-900">Abuse Monitoring</h3>
              <p className="text-sm leading-relaxed text-slate-600">
                Traffic patterns are monitored for anomalies. Suspicious activity triggers
                automatic rate-limiting and manual review. Violations are reported and
                accounts terminated.
              </p>
            </div>
            <div className="rounded-2xl border border-slate-200 bg-white p-6">
              <Radar className="mb-3 h-6 w-6 text-primary" />
              <h3 className="mb-2 font-semibold text-slate-900">Regulatory Compliance</h3>
              <p className="text-sm leading-relaxed text-slate-600">
                TCPA, GDPR, CCPA, and CAN-SPAM compliant. All integrations are reviewed
                for acceptable use and restricted to transactional and security-related
                application workflows.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Reliability */}
      <section className="py-20">
        <SectionHeading
          title="Reliability & Infrastructure"
          subtitle="Production-grade infrastructure designed for consistent uptime and predictable performance."
        />
        <div className="mx-auto max-w-4xl px-6">
          <div className="grid gap-6 sm:grid-cols-3">
            <div className="rounded-2xl border border-slate-200 bg-white p-6 text-center">
              <Server className="mx-auto mb-3 h-6 w-6 text-primary" />
              <p className="text-2xl font-bold text-slate-900">99.9%</p>
              <p className="text-sm text-slate-600">Uptime SLA target</p>
            </div>
            <div className="rounded-2xl border border-slate-200 bg-white p-6 text-center">
              <Gauge className="mx-auto mb-3 h-6 w-6 text-primary" />
              <p className="text-2xl font-bold text-slate-900">60 req/s</p>
              <p className="text-sm text-slate-600">Default rate limit per API key</p>
            </div>
            <div className="rounded-2xl border border-slate-200 bg-white p-6 text-center">
              <LifeBuoy className="mx-auto mb-3 h-6 w-6 text-primary" />
              <p className="text-2xl font-bold text-slate-900">&lt; 4h</p>
              <p className="text-sm text-slate-600">Incident response time</p>
            </div>
          </div>
          <p className="mt-8 text-center text-sm text-slate-500">
            Higher rate limits available on request. For incidents or urgent issues, contact{" "}
            <a href="mailto:support@unisynthe.com" className="text-primary hover:underline">
              support@unisynthe.com
            </a>.
          </p>
        </div>
      </section>

      {/* CTA */}
      <section className="bg-slate-50 py-20">
        <div className="mx-auto max-w-2xl px-6 text-center">
          <h2 className="mb-4 text-2xl font-bold text-slate-900">Ready to integrate?</h2>
          <p className="mb-8 text-slate-600">
            Tell us about your application and we'll review your integration within one business day.
          </p>
          <Link
            to="/request-access"
            className="inline-block rounded-lg bg-primary px-8 py-3 text-sm font-medium text-white shadow-sm transition-colors hover:bg-primary-dark"
          >
            Request API Access
          </Link>
        </div>
      </section>
    </>
  );
}
